### ISSUE TITLE
Testcase 1 incorrect output mismatch 

### ISSUE THREAD

**Issue by azzamasim** [JZJisawesome/ece250-testcases#17]
My code passes all tests and memory checks except Testcase 1 (chatgpt_autogenerated_0), it says failed due to output mismatch on line 0.

So I tested this case individually. Turns out, the only difference is my output has an extra newline at the end that the expected output doesn't. This is because the last command is a PRT, and as per the specification in the project guidelines you need to print a newline character, so the output should have a blank line at the end (at least in my understanding).

The weirdest thing is, virtually everyone else is passing that test case. When I checked their output, they also have that extra newline at the end. Don't know how useful this is since submission is in 2.5 hours, but I figured I might as well open an issue so we can keep track of it. I think the chatgpt_autogenerated_0.out should be changed so that it has that extra newline at the end. 

Some screenshots to better illustrate this:
![Screenshot 2023-01-27 at 8 00 06 PM](https://user-images.githubusercontent.com/84571967/215234265-6be0d169-379a-4ff5-9365-27ecd919bd6c.png)
![Screenshot 2023-01-27 at 8 15 17 PM](https://user-images.githubusercontent.com/84571967/215234275-151d13d8-d6f4-456a-9822-2f9f886426a5.png)

**Comment by JZJisawesome** [comment]
Thanks for this! I found this to be a similar issue for the Project 2 testcases. We now trim whitespace at the end of the line before comparing the lines, so this should be fixed.
