### ISSUE TITLE
Invalid Test Case: tiny_circles

### ISSUE THREAD

**Issue by ReezanVisram** [JZJisawesome/ece250-testcases#36]
Hi John,

The tiny_circles test case inserts an edge from a vertex to itself, which according to this answer on Piazza is invalid (https://piazza.com/class/lbtsz4p4fg54e2/post/423).

Just wanted to let you know.

Thanks

**Comment by ReezanVisram** [comment]
This also applies to tiny_circles_the_sequel and tiny_circles_trilogy.

**Comment by JZJisawesome** [comment]
Hi, as I mentioned on Piazza, there are several invalid P4 testcases at the moment, and datasets too. vertex_weight_limits for example is also invalid.

I will get to this as soon as I have time.
