### ISSUE TITLE
Pushpopyum, invalid input

### ISSUE THREAD

**Issue by RyEggGit** [JZJisawesome/ece250-testcases#6]
Lmk if I wrong but I'm pretty sure "REM" only takes in a variable name not a variable name and variable value.

Old Case:
- CRT 100
- DEF x 123
- REM x
- DEF x 456
- DEF y 789
- REM x 123
- REM y 123
- DEF x 0
- DEF y 1
- DEF z 2
- REM y
- REM z
- REM x
- DEF y 1111
- DEF x 2222
- DEF z 3333
- REM y
- REM x
- REM z
- END

New Case:
- CRT 100
- DEF x 123
- REM x
- DEF x 456
- DEF y 789
- REM x
- REM y
- DEF x 0
- DEF y 1
- DEF z 2
- REM y
- REM z
- REM x
- DEF y 1111
- DEF x 2222
- DEF z 3333
- REM y
- REM x
- REM z
- END

**Comment by JZJisawesome** [comment]
Shoot, my bad. I will fix this shortly

**Comment by JZJisawesome** [comment]
Fixed
